=== rockitconsulting/integration-platform/IIB-HealthMon/IIB-HealthMon/healthmon.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- W3C Schema generated by XMLSpy v2016 rel. 2 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="healthmon">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="connectors">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="connector" maxOccurs="unbounded">
								<xs:complexType>
									<xs:choice>
										<xs:element name="http" type="HTTPConnectorType" />
										<xs:element name="jks" type="JKSConnectorType" />
										<xs:element name="mq" type="MQConnectorType" />
										<xs:element name="db" type="DBConnectorType" />
									</xs:choice>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="reports">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="report" maxOccurs="unbounded">
								<xs:complexType>
									<xs:choice>
										<xs:element name="kafka" type="KAFKAConnectorType" />
										<xs:element name="mail" type="MAILConnectorType" />
										<xs:element name="file" type="FILEConnectorType" />
										<xs:element name="jms" type="JMSConnectorType" />
										<xs:element name="mq" type="MQConnectorType" />
									</xs:choice>
									<xs:attribute name="level" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="All" />
												<xs:enumeration value="Error" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="targetNamespace" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:anyURI">
												<xs:enumeration value="http://com.rockit/healthmon/report" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="targetNamespace" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:anyURI">
						<xs:enumeration value="http://com.rockit/healthmon" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="HTTPConnectorType">
		<xs:sequence>
			<xs:element name="property" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="name" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="HTTPRequestHeader.Authorization" />
								<xs:enumeration value="HTTPRequestHeader.Content-Type" />
								<xs:enumeration value="Id" />
								<xs:enumeration value="RequestLine.Method" />
								<xs:enumeration value="RequestURL" />
								<xs:enumeration value="SSLProtocol" />
								<xs:enumeration value="LbStatus" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="value" use="required" type="xs:string" />
				</xs:complexType>
			</xs:element>
			<xs:element name="requesttemplate" minOccurs="0" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="JKSConnectorType">
		<xs:sequence>
			<xs:element name="property" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="name" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="Id" />
								<xs:enumeration value="TrustStoreFileName" />
								<xs:enumeration value="TrustStorePwd" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="value" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string" />
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="targetNamespace" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:anyURI">
					<xs:enumeration value="http://com.rockit/healthmon/connector/jks" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="MQConnectorType">
		<xs:sequence>
			<xs:element name="property" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="name" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="Id" />
								<xs:enumeration value="QueueName" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="value" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string" />
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="targetNamespace" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:anyURI">
					<xs:enumeration value="http://com.rockit/healthmon/connector/mq" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="DBConnectorType">
		<xs:sequence>
			<xs:element name="property" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="name" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="DBSchema" />
								<xs:enumeration value="DBTable" />
								<xs:enumeration value="Id" />
								<xs:enumeration value="ODBCDatasource" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="value" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string" />
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="targetNamespace" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:anyURI">
					<xs:enumeration value="http://com.rockit/healthmon/connector/db" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="KAFKAConnectorType">
		<xs:sequence>
			<xs:element name="property">
				<xs:complexType>
					<xs:attribute name="name" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="kafkaConfigProperty" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="value" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string" />
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="targetNamespace" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:anyURI">
					<xs:enumeration value="http://com.rockit/healthmon/connector/kafka" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="MAILConnectorType">
		<xs:sequence>
			<xs:element name="property" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="name" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="CC" />
								<xs:enumeration value="Directory" />
								<xs:enumeration value="FileName" />
								<xs:enumeration value="Receiver" />
								<xs:enumeration value="SMTPServer" />
								<xs:enumeration value="Sender" />
								<xs:enumeration value="SecurityIdentity" />
								<xs:enumeration value="BodyContentType" />
								<xs:enumeration value="AttachmentContent" />
								<xs:enumeration value="AttachmentContentType" />
								<xs:enumeration value="AttachmentContentName" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="value" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string" />
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="targetNamespace" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:anyURI">
					<xs:enumeration value="http://com.rockit/healthmon/connector/mail" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="FILEConnectorType">
		<xs:sequence>
			<xs:element name="property" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="name" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="CC" />
								<xs:enumeration value="Directory" />
								<xs:enumeration value="FileName" />
								<xs:enumeration value="Port" />
								<xs:enumeration value="Receiver" />
								<xs:enumeration value="SMTPServer" />
								<xs:enumeration value="Sender" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="value" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string" />
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="targetNamespace" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:anyURI">
					<xs:enumeration value="http://com.rockit/healthmon/connector/file" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="JMSConnectorType">
		<xs:sequence>
			<xs:element name="property" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="name" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="qName" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="value" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:anyURI" />
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="targetNamespace" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:anyURI">
					<xs:enumeration value="http://com.rockit/healthmon/connector/jms" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== rockitconsulting/integration-platform/IIB-HealthMon/IIB-HealthMon/docs/00_ALL_HM_TEST_CFG.xml
<?xml version="1.0" encoding="UTF-8"?>
<healthmon xmlns:n1="http://www.w3.org/2001/XMLSchema-instance" targetNamespace="http://com.rockit/healthmon" n1:noNamespaceSchemaLocation="C:\rockit\projects\rockitsvn_transition\IIB-HealthMon\IIB-HealthMon\healthmon.xsd">
	<connectors>
		<connector>
			<db targetNamespace="http://com.rockit/healthmon/connector/db">
				<property name="Id" value=""/>
				<property name="ODBCDatasource" value=""/>
				<property name="DBSchema" value=""/>
				<property name="DBTable" value=""/>
			</db>
		</connector>
		<connector>
			<http xmlns:http="http://com.rockit/healthmon/connector/http">
				<property name="Id" value=""/>
				<property name="LbStatus" value=""/>
				<property name="HTTPRequestHeader.Authorization" value=""/>
				<property name="HTTPRequestHeader.Content-Type" value="text/xml"/>
				<property name="RequestURL" value=""/>
				<property name="RequestLine.Method" value="POST"/>
				<property name="SSLProtocol" value="SSL_TLSv2"/>
				<requesttemplate><![CDATA[<body></body>]]></requesttemplate>
			</http>
		</connector>
		<connector>
			<http xmlns:http="http://com.rockit/healthmon/connector/http">
				<property name="Id" value=""/>
				<property name="LbStatus" value=""/>
				<property name="HTTPRequestHeader.Authorization" value=""/>
				<property name="HTTPRequestHeader.Content-Type" value="text/xml"/>
				<property name="RequestURL" value=""/>
				<property name="RequestLine.Method" value="GET"/>
				<property name="SSLProtocol" value=""/>
				<requesttemplate><![CDATA[<body></body>]]></requesttemplate>
			</http>
		</connector>
		<connector>
			<jks targetNamespace="http://com.rockit/healthmon/connector/jks">
				<property name="Id" value=""/>
				<property name="TrustStoreFileName" value=""/>
				<property name="TrustStorePwd" value=""/>
			</jks>
		</connector>
		<connector>
			<mq targetNamespace="http://com.rockit/healthmon/connector/mq">
				<property name="Id" value=""/>
				<property name="QueueName" value=""/>
			</mq>
		</connector>
		<connector>
			<jks targetNamespace="http://com.rockit/healthmon/connector/jks">
				<property name="Id" value=""/>
				<property name="TrustStoreFileName" value=""/>
				<property name="TrustStorePwd" value=""/>
			</jks>
		</connector>
	</connectors>
	<reports>
	
		<report level="All" targetNamespace="http://com.rockit/healthmon/report">
			<mq targetNamespace="http://com.rockit/healthmon/connector/mq">
				<property name="QueueName" value=""/>
			</mq>
		</report>
		
		<report level="All" targetNamespace="http://com.rockit/healthmon/report">
			<mail targetNamespace="http://com.rockit/healthmon/connector/mail">
				<property name="SMTPServer" value=""/>
				<property name="Sender" value=""/>
				<property name="Receiver" value=""/>
				<property name="CC" value=""/> 	
				<property name="SecurityIdentity" value=""/> 
				<property name="BodyContentType" value="text/html"/>
				<property name="AttachmentContentName" value=""/>
			</mail>
		</report>
	
	
		<report level="All" targetNamespace="http://com.rockit/healthmon/report">
			<file targetNamespace="http://com.rockit/healthmon/connector/file">
				<property name="Directory" value=""/>
				<property name="FileName" value=""/>
			</file>
		</report>
		
		<report level="All" targetNamespace="http://com.rockit/healthmon/report">
			<jms targetNamespace="http://com.rockit/healthmon/connector/jms">
				<property name="qName" value=""/>
				<property name="qName" value=""/>
				<property name="qName" value=""/>
				<property name="qName" value=""/>
			</jms>
		</report>
		
	<!--	
		<report level="All" targetNamespace="http://com.rockit/healthmon/report">
			<kafka targetNamespace="http://com.rockit/healthmon/connector/kafka">
				<property name="kafkaConfigProperty" value=""/>
			</kafka>
		</report>
	-->	
	</reports>
</healthmon>
